"use client";

import { useActionState, useState } from "react";
import { submitSurveyAction, type SurveyState } from "@/app/consumidor/pesquisas/actions";
import { submitCampaignAction } from "@/app/campaigns/[slug]/actions";

export type SurveyQuestion={id:string;pergunta:string;tipo:string;opcoes:unknown;ordem:number};
type Answer=string|string[]|number;

export function SurveyFlow({questionnaireId,questions,campaignSlug,defaultCity="",defaultNeighborhood="",utmSource="",utmMedium="",utmCampaign=""}:{questionnaireId:string;questions:SurveyQuestion[];campaignSlug?:string;defaultCity?:string;defaultNeighborhood?:string;utmSource?:string;utmMedium?:string;utmCampaign?:string}){
  const submitAction=campaignSlug?submitCampaignAction:submitSurveyAction;const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Record<string,Answer>>({});const [localError,setLocalError]=useState("");const [state,action,pending]=useActionState(submitAction,{} as SurveyState);const question=questions[index];const answer=answers[question.id];
  function valid(){if(question.tipo==="multiple_choice")return Array.isArray(answer)&&answer.length>0;if(question.tipo==="short_text")return typeof answer==="string"&&answer.trim().length>0;return answer!==undefined&&answer!==""}
  function next(){if(!valid())return setLocalError("Escolha ou informe uma resposta para continuar.");setLocalError("");setIndex(current=>Math.min(questions.length-1,current+1))}
  function setAnswer(value:Answer){setAnswers(current=>({...current,[question.id]:value}));setLocalError("")}
  return <form action={action} className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/40 sm:p-9"><input type="hidden" name="questionnaire_id" value={questionnaireId}/>{campaignSlug&&<><input type="hidden" name="slug" value={campaignSlug}/><input type="hidden" name="utm_source" value={utmSource}/><input type="hidden" name="utm_medium" value={utmMedium}/><input type="hidden" name="utm_campaign" value={utmCampaign}/><div className="mb-7 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Cidade (opcional)<input name="cidade" defaultValue={defaultCity} maxLength={100} className="consumer-input mt-2"/></label><label className="text-sm font-semibold text-slate-700">Bairro (opcional)<input name="bairro" defaultValue={defaultNeighborhood} maxLength={100} className="consumer-input mt-2"/></label></div></>}<input type="hidden" name="answers" value={JSON.stringify(answers)}/><div className="flex items-center justify-between gap-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-teal-700">Pergunta {index+1} de {questions.length}</p><span className="text-xs text-slate-400">{Math.round(((index+1)/questions.length)*100)}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-[width]" style={{width:`${((index+1)/questions.length)*100}%`}}/></div><fieldset className="mt-9"><legend className="text-balance text-2xl font-semibold leading-8 text-slate-950">{question.pergunta}</legend><div className="mt-7"><QuestionInput question={question} answer={answer} setAnswer={setAnswer}/></div></fieldset>{(localError||state.error)&&<p role="alert" className="mt-6 rounded-xl bg-red-50 p-3.5 text-sm text-red-700">{localError||state.error}</p>}<div className="mt-9 flex justify-between gap-3"><button type="button" onClick={()=>{setLocalError("");setIndex(current=>Math.max(0,current-1))}} disabled={index===0||pending} className="button-secondary disabled:invisible">Voltar</button>{index<questions.length-1?<button type="button" onClick={next} className="button-primary">Continuar</button>:<button type="submit" disabled={pending} onClick={event=>{if(!valid()){event.preventDefault();setLocalError("Responda esta pergunta antes de enviar.")}}} className="button-primary disabled:opacity-60">{pending?"Enviando...":"Enviar respostas"}</button>}</div></form>}

function QuestionInput({question,answer,setAnswer}:{question:SurveyQuestion;answer:Answer|undefined;setAnswer:(value:Answer)=>void}){if(question.tipo==="short_text")return <label><span className="sr-only">Resposta curta</span><input autoFocus maxLength={300} value={typeof answer==="string"?answer:""} onChange={e=>setAnswer(e.target.value)} className="consumer-input" placeholder="Digite sua resposta"/></label>;if(question.tipo==="scale"){const config=record(question.opcoes);const min=number(config.min,1);const max=number(config.max,5);return <div className="flex flex-wrap gap-3">{Array.from({length:max-min+1},(_,i)=>i+min).map(value=><button type="button" key={value} onClick={()=>setAnswer(value)} aria-pressed={answer===value} className={`grid size-12 place-items-center rounded-xl border text-sm font-bold transition ${answer===value?"border-teal-600 bg-teal-600 text-white":"border-slate-200 bg-white text-slate-700 hover:border-teal-300"}`}>{value}</button>)}</div>};const options=array(question.opcoes);if(question.tipo==="multiple_choice"){const selected=Array.isArray(answer)?answer:[];return <div className="grid gap-3 sm:grid-cols-2">{options.map(option=><label key={option} className="cursor-pointer"><input type="checkbox" className="peer sr-only" checked={selected.includes(option)} onChange={()=>setAnswer(selected.includes(option)?selected.filter(item=>item!==option):[...selected,option])}/><span className="flex min-h-12 items-center rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-700 peer-checked:border-teal-600 peer-checked:bg-teal-50 peer-checked:text-teal-800 peer-focus-visible:ring-4 peer-focus-visible:ring-teal-600/15">{option}</span></label>)}</div>};return <div className="grid gap-3 sm:grid-cols-2">{options.map(option=><label key={option} className="cursor-pointer"><input type="radio" name={`question-${question.id}`} className="peer sr-only" checked={answer===option} onChange={()=>setAnswer(option)}/><span className="flex min-h-12 items-center rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-700 peer-checked:border-teal-600 peer-checked:bg-teal-50 peer-checked:text-teal-800 peer-focus-visible:ring-4 peer-focus-visible:ring-teal-600/15">{option}</span></label>)}</div>}
function record(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>: {}}
function array(value:unknown):string[]{return Array.isArray(value)?value.filter(item=>typeof item==="string"):[]}
function number(value:unknown,fallback:number){return typeof value==="number"&&Number.isInteger(value)?value:fallback}
