import Link from "next/link";
import { ChartIcon, SearchIcon } from "@/components/ui/icons";
import { buildRecommendation, growthPercentage, trendLabel, type GapInput } from "@/lib/market-intelligence/rules";

export type RankingItem={label:string;current:number;previous:number;growth_pct:number|null};
export type RawGap={category?:string;term?:string;demand:number;previous_demand:number;supply:number;kind:GapInput["kind"]};
export type QuestionnaireSignal={question:string;answer:string;count:number;respondents:number};
export type IntelligenceData={meta:{period_days:number;scope:string;city:string;neighborhood:string;segment:string;ranking_threshold:number;questionnaire_respondent_threshold:number};kpis:{total_searches:number;segment_searches:number;week_current:number;week_previous:number;month_current:number;month_previous:number};top_terms:RankingItem[];categories:RankingItem[];market_gaps:RawGap[];product_gaps:RawGap[];questionnaire_signals:QuestionnaireSignal[]};

export function IntelligenceDashboard({data,period,scope}:{data:IntelligenceData;period:number;scope:"neighborhood"|"city"}){
  const weekGrowth=growthPercentage(data.kpis.week_current,data.kpis.week_previous);const monthGrowth=growthPercentage(data.kpis.month_current,data.kpis.month_previous);
  const gaps:GapInput[]=[...(data.product_gaps??[]).map(item=>({label:item.term??"Produto",demand:item.demand,previousDemand:item.previous_demand,supply:item.supply,kind:item.kind,dimension:"product" as const})),...(data.market_gaps??[]).map(item=>({label:item.category??"Categoria",demand:item.demand,previousDemand:item.previous_demand,supply:item.supply,kind:item.kind,dimension:"category" as const}))];
  const recommendations=gaps.map(buildRecommendation).filter((item):item is NonNullable<typeof item>=>Boolean(item)).slice(0,4);
  const hasRankings=data.top_terms.length>0||data.categories.length>0;
  return <section className="mt-12 border-t border-slate-200 pt-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="section-kicker">Inteligência de mercado</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.025em] text-slate-950 sm:text-3xl">Sinais reais da sua região</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Agregados de buscas e pesquisas, sem dados pessoais. A leitura atual considera {scope==="city"?`a cidade de ${data.meta.city}`:`${data.meta.neighborhood}, ${data.meta.city}`}.</p></div><div className="flex flex-wrap gap-2"><FilterGroup values={[7,30,90]} current={period} scope={scope}/><ScopeGroup current={scope} period={period}/></div></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi label={`Buscas em ${period} dias`} value={data.kpis.total_searches}/><Kpi label={`Buscas em ${data.meta.segment}`} value={data.kpis.segment_searches}/><Comparison label="Comparação semanal" current={data.kpis.week_current} previous={data.kpis.week_previous} growth={weekGrowth}/><Comparison label="Comparação mensal" current={data.kpis.month_current} previous={data.kpis.month_previous} growth={monthGrowth}/></div>
    {!hasRankings?<NoData threshold={data.meta.ranking_threshold}/>:<div className="mt-7 grid gap-6 lg:grid-cols-2"><Ranking title="Produtos e termos mais buscados" items={data.top_terms} icon={SearchIcon}/><Ranking title="Categorias mais pesquisadas" items={data.categories} icon={ChartIcon}/></div>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Recommendations items={recommendations}/><QuestionnaireSignals items={data.questionnaire_signals??[]} threshold={data.meta.questionnaire_respondent_threshold}/></div>
    <p className="mt-5 text-xs leading-5 text-slate-400">Regra de lacuna: demanda relevante começa em 5 buscas; oferta baixa significa até 2 produtos disponíveis (ou até 3 quando a demanda cresce). Rankings só exibem sinais com pelo menos {data.meta.ranking_threshold} ocorrências.</p>
  </section>;
}

function FilterGroup({values,current,scope}:{values:number[];current:number;scope:string}){return <div className="flex rounded-full border border-slate-200 bg-white p-1">{values.map(value=><Link key={value} href={`/comerciante?periodo=${value}&escopo=${scope}`} className={`rounded-full px-3 py-1.5 text-xs font-bold ${value===current?"bg-slate-950 text-white":"text-slate-500 hover:text-slate-900"}`}>{value} dias</Link>)}</div>}
function ScopeGroup({current,period}:{current:string;period:number}){return <div className="flex rounded-full border border-slate-200 bg-white p-1">{[["neighborhood","Bairro"],["city","Cidade"]].map(([value,label])=><Link key={value} href={`/comerciante?periodo=${period}&escopo=${value}`} className={`rounded-full px-3 py-1.5 text-xs font-bold ${value===current?"bg-teal-700 text-white":"text-slate-500 hover:text-slate-900"}`}>{label}</Link>)}</div>}
function Kpi({label,value}:{label:string;value:number}){return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-2xl font-semibold text-slate-950">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{label}</p></article>}
function Comparison({label,current,previous,growth}:{label:string;current:number;previous:number;growth:number|null}){const tone=growth===null?"text-teal-700":growth>0?"text-teal-700":growth<0?"text-red-600":"text-slate-500";return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-baseline justify-between gap-2"><p className="text-2xl font-semibold text-slate-950">{current}</p><span className={`text-xs font-bold ${tone}`}>{growth===null?(current?"Novo":"Sem variação"):`${growth>0?"+":""}${growth}%`}</span></div><p className="mt-2 text-xs text-slate-500">{label} · anterior: {previous}</p></article>}
function Ranking({title,items,icon:Icon}:{title:string;items:RankingItem[];icon:typeof SearchIcon}){const max=Math.max(...items.map(item=>item.current),1);return <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon className="size-5"/></div><h3 className="font-semibold text-slate-950">{title}</h3></div><ol className="mt-6 space-y-5">{items.slice(0,6).map((item,index)=><li key={item.label}><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate font-medium text-slate-800"><strong className="mr-2 text-slate-400">{index+1}</strong>{item.label}</span><span className="shrink-0 text-xs text-slate-500">{item.current} · <span className={item.current>=item.previous?"text-teal-700":"text-red-600"}>{trendLabel(item.current,item.previous)}</span></span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{width:`${Math.max(8,(item.current/max)*100)}%`}}/></div></li>)}</ol></article>}
function Recommendations({items}:{items:NonNullable<ReturnType<typeof buildRecommendation>>[]}){return <article className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-300">Oportunidades e atenção</p><h3 className="mt-2 text-xl font-semibold">Recomendações por regras</h3>{items.length?<ul className="mt-5 space-y-3">{items.map((item,index)=><li key={`${item.message}-${index}`} className="rounded-2xl bg-white/7 p-4"><p className="text-sm leading-6 text-slate-200">{item.message}</p><span className="mt-2 inline-block text-[10px] font-bold uppercase tracking-wider text-teal-300">Confiança {item.confidence==="high"?"alta":item.confidence==="medium"?"média":"baixa"}</span></li>)}</ul>:<p className="mt-5 rounded-2xl bg-white/7 p-5 text-sm leading-6 text-slate-300">Ainda não há volume suficiente para recomendações responsáveis.</p>}</article>}
function QuestionnaireSignals({items,threshold}:{items:QuestionnaireSignal[];threshold:number}){return <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="section-kicker">Pesquisas agregadas</p><h3 className="mt-2 text-xl font-semibold text-slate-950">Principais sinais</h3>{items.length?<ul className="mt-5 divide-y divide-slate-100">{items.slice(0,6).map((item,index)=><li key={`${item.question}-${item.answer}-${index}`} className="py-3"><p className="line-clamp-1 text-xs text-slate-500">{item.question}</p><div className="mt-1 flex justify-between gap-3"><span className="text-sm font-semibold text-slate-800">{item.answer}</span><span className="text-xs text-slate-400">{item.count} seleções</span></div></li>)}</ul>:<p className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm leading-6 text-slate-500">Os sinais aparecem quando uma pesquisa alcança pelo menos {threshold} respondentes na região.</p>}</article>}
function NoData({threshold}:{threshold:number}){return <div className="mt-7 rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><ChartIcon className="mx-auto size-8 text-slate-400"/><h3 className="mt-4 font-semibold text-slate-900">Insights em formação</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">Os rankings aparecerão quando um termo ou categoria tiver pelo menos {threshold} buscas na região e no período selecionado.</p></div>}
