"use client";

import { useActionState } from "react";
import { createCompanyAction, updateCompanyAction, type MerchantState } from "@/app/comerciante/actions";
import { INTEREST_CATEGORIES } from "@/lib/consumer/categories";

type Company={nome_fantasia:string;razao_social:string|null;cnpj:string|null;categoria:string;endereco:string;cidade:string;bairro:string;latitude:number|null;longitude:number|null;horario_funcionamento:unknown;telefone:string|null;whatsapp:string|null;email:string;redes_sociais:unknown};
export function CompanyForm({company}: {company?:Company}){const action=company?updateCompanyAction:createCompanyAction;const [state,formAction,pending]=useActionState(action,{} as MerchantState);const social=asRecord(company?.redes_sociais);const hours=asRecord(company?.horario_funcionamento).resumo;return <form action={formAction} className="mt-8 space-y-8"><section><h2 className="text-lg font-semibold text-slate-950">Identificação</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><Field label="Nome fantasia" name="nome_fantasia" defaultValue={company?.nome_fantasia}/><Field label="Razão social (opcional)" name="razao_social" defaultValue={company?.razao_social}/><Field label="CNPJ (opcional)" name="cnpj" defaultValue={company?.cnpj} placeholder="Somente números"/><Select label="Categoria" name="categoria" defaultValue={company?.categoria}/></div></section><section><h2 className="text-lg font-semibold text-slate-950">Localização e funcionamento</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Endereço" name="endereco" defaultValue={company?.endereco}/></div><Field label="Cidade" name="cidade" defaultValue={company?.cidade}/><Field label="Bairro" name="bairro" defaultValue={company?.bairro}/><Field label="Latitude (opcional)" name="latitude" defaultValue={company?.latitude?.toString()} placeholder="Ex.: -23.5505"/><Field label="Longitude (opcional)" name="longitude" defaultValue={company?.longitude?.toString()} placeholder="Ex.: -46.6333"/><p className="sm:col-span-2 text-xs leading-5 text-slate-500">Coordenadas do endereço comercial podem ser obtidas gratuitamente no OpenStreetMap. A posição precisa do consumidor não é armazenada.</p><div className="sm:col-span-2"><Field label="Horário de funcionamento" name="horario" defaultValue={typeof hours==="string"?hours:""} placeholder="Ex.: Segunda a sábado, 8h às 18h"/></div></div></section><section><h2 className="text-lg font-semibold text-slate-950">Contato</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><Field label="Telefone (opcional)" name="telefone" defaultValue={company?.telefone}/><Field label="WhatsApp (opcional)" name="whatsapp" defaultValue={company?.whatsapp}/><Field label="Email comercial" name="email" type="email" defaultValue={company?.email}/><Field label="Instagram (opcional)" name="instagram" defaultValue={stringValue(social.instagram)}/><Field label="Facebook (opcional)" name="facebook" defaultValue={stringValue(social.facebook)}/><Field label="Site (opcional)" name="site" defaultValue={stringValue(social.site)}/></div></section>{(state.error||state.success)&&<p role="status" className={`rounded-xl p-3.5 text-sm ${state.error?"bg-red-50 text-red-700":"bg-teal-50 text-teal-800"}`}>{state.error??state.success}</p>}<button disabled={pending} className="button-primary disabled:opacity-60">{pending?"Salvando...":company?"Salvar alterações":"Criar minha empresa"}</button></form>}
function Field({label,type="text",defaultValue,...props}:{label:string;name:string;type?:string;defaultValue?:string|null;placeholder?:string}){return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input {...props} type={type} defaultValue={defaultValue??""} required={!label.includes("opcional")} className="consumer-input"/></label>}
function Select({label,name,defaultValue}:{label:string;name:string;defaultValue?:string}){return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><select name={name} defaultValue={defaultValue??""} required className="consumer-input"><option value="" disabled>Selecione</option>{INTEREST_CATEGORIES.map(item=><option key={item}>{item}</option>)}</select></label>}
function asRecord(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function stringValue(value:unknown){return typeof value==="string"?value:""}
