"use client";

import { useActionState } from "react";
import { createProductAction, updateProductAction, type MerchantState } from "@/app/comerciante/actions";
import { INTEREST_CATEGORIES } from "@/lib/consumer/categories";

type Product={id:string;nome:string;categoria:string;marca:string|null;quantidade:number;status:string};
export function ProductForm({product}:{product?:Product}){const action=product?updateProductAction:createProductAction;const [state,formAction,pending]=useActionState(action,{} as MerchantState);return <form action={formAction} className="mt-8 space-y-6">{product&&<input type="hidden" name="id" value={product.id}/>}<div className="grid gap-5 sm:grid-cols-2"><Field label="Nome do produto" name="nome" defaultValue={product?.nome}/><Field label="Marca (opcional)" name="marca" defaultValue={product?.marca}/><label><span className="mb-2 block text-sm font-semibold text-slate-700">Categoria</span><select required name="categoria" defaultValue={product?.categoria??""} className="consumer-input"><option value="" disabled>Selecione</option>{INTEREST_CATEGORIES.map(item=><option key={item}>{item}</option>)}</select></label><Field label="Quantidade" name="quantidade" type="number" min="0" step="1" defaultValue={String(product?.quantidade??0)}/><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold text-slate-700">Disponibilidade</span><select required name="status" defaultValue={product?.status??"available"} className="consumer-input"><option value="available">Disponível</option><option value="low_stock">Estoque baixo</option><option value="unavailable">Indisponível</option></select></label></div>{(state.error||state.success)&&<p role="status" className={`rounded-xl p-3.5 text-sm ${state.error?"bg-red-50 text-red-700":"bg-teal-50 text-teal-800"}`}>{state.error??state.success}</p>}<button disabled={pending} className="button-primary disabled:opacity-60">{pending?"Salvando...":product?"Salvar produto":"Cadastrar produto"}</button></form>}
function Field({label,type="text",defaultValue,...props}:{label:string;name:string;type?:string;defaultValue?:string|null;min?:string;step?:string}){return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input {...props} type={type} defaultValue={defaultValue??""} required={!label.includes("opcional")} className="consumer-input"/></label>}
