"use client";

import { useActionState } from "react";
import { createQuestionAction,deleteQuestionAction,updateQuestionAction,type AdminSurveyState } from "@/app/admin/questionarios/actions";

type Question={id:string;pergunta:string;tipo:string;opcoes:unknown;ordem:number};
export function QuestionEditor({questionnaireId,question,locked=false}:{questionnaireId:string;question?:Question;locked?:boolean}){
  const [state,action,pending]=useActionState(question?updateQuestionAction:createQuestionAction,{} as AdminSurveyState);
  const [deleteState,deleteAction,deletePending]=useActionState(deleteQuestionAction,{} as AdminSurveyState);
  if(locked)return question?<div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="font-semibold text-slate-900">{question.pergunta}</p><p className="mt-2 text-xs text-slate-500">{typeLabel(question.tipo)} · preservada após a primeira resposta</p></div>:<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Não é possível adicionar perguntas depois que o questionário recebe respostas.</div>;
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><form action={action} className="space-y-4"><input type="hidden" name="questionnaire_id" value={questionnaireId}/>{question&&<input type="hidden" name="id" value={question.id}/>}<label><span className="mb-2 block text-sm font-semibold text-slate-700">Pergunta</span><input required name="pergunta" defaultValue={question?.pergunta} className="consumer-input" placeholder="Escreva uma pergunta curta"/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold text-slate-700">Tipo</span><select required name="tipo" defaultValue={question?.tipo??"single_choice"} className="consumer-input"><option value="single_choice">Escolha única</option><option value="multiple_choice">Múltipla escolha</option><option value="short_text">Texto curto</option><option value="scale">Escala numérica</option></select></label><label><span className="mb-2 block text-sm font-semibold text-slate-700">Opções ou escala</span><textarea name="opcoes" defaultValue={formatOptions(question?.tipo,question?.opcoes)} rows={3} placeholder={'Alternativas: uma por linha\nEscala: 1-5'} className="w-full rounded-xl border border-slate-300 p-3 text-sm outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-600/10"/></label></div>{(state.error||state.success)&&<p className={`text-sm ${state.error?"text-red-600":"text-teal-700"}`}>{state.error??state.success}</p>}<button disabled={pending} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white hover:bg-teal-700 disabled:opacity-50">{pending?"Salvando...":question?"Salvar pergunta":"Adicionar pergunta"}</button></form>{question&&<form action={deleteAction} onSubmit={event=>{if(!window.confirm("Remover esta pergunta?"))event.preventDefault()}} className="mt-3"><input type="hidden" name="questionnaire_id" value={questionnaireId}/><input type="hidden" name="id" value={question.id}/><button disabled={deletePending} className="text-xs font-bold text-red-600 hover:text-red-700">{deletePending?"Removendo...":"Remover pergunta"}</button>{deleteState.error&&<p className="mt-2 text-xs text-red-600">{deleteState.error}</p>}</form>}</div>
}
function formatOptions(type:string|undefined,value:unknown){if((type==="single_choice"||type==="multiple_choice")&&Array.isArray(value))return value.join("\n");if(type==="scale"&&value&&typeof value==="object"&&!Array.isArray(value)){const record=value as Record<string,unknown>;return `${record.min??1}-${record.max??5}`}return ""}
function typeLabel(type:string){return type==="single_choice"?"Escolha única":type==="multiple_choice"?"Múltipla escolha":type==="short_text"?"Texto curto":"Escala numérica"}
