import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { SurveyFlow, type SurveyQuestion } from "@/components/questionnaires/survey-flow";
import { consumerProfileComplete, requireRole } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";

export const metadata:Metadata={title:"Responder pesquisa"};
export default async function Page({params}:{params:Promise<{id:string}>}){const {user,profile}=await requireRole("consumer");if(!consumerProfileComplete(profile))redirect("/consumidor/onboarding");const {id}=await params;const supabase=await createClient();const [{data:survey,error},{data:questions},{data:submission}]=await Promise.all([supabase.from("questionnaires").select("id,titulo,descricao,estimated_minutes").eq("id",id).eq("ativo",true).single(),supabase.from("questionnaire_questions").select("id,pergunta,tipo,opcoes,ordem").eq("questionnaire_id",id).order("ordem"),supabase.from("questionnaire_submissions").select("id").eq("questionnaire_id",id).eq("consumer_id",user.id).maybeSingle()]);if(error||!survey)notFound();if(submission)redirect("/consumidor/pesquisas");if(!questions?.length)return <main className="container-shell flex-1 py-12"><p className="rounded-2xl bg-amber-50 p-5 text-amber-800">Esta pesquisa ainda não possui perguntas.</p></main>;return <main className="container-shell flex-1 py-10 sm:py-14"><div className="mx-auto max-w-2xl"><Link href="/consumidor/pesquisas" className="text-sm font-bold text-teal-700">← Voltar para pesquisas</Link><p className="section-kicker mt-7">Pesquisa rápida · {survey.estimated_minutes} min</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.035em] text-slate-950 sm:text-4xl">{survey.titulo}</h1>{survey.descricao&&<p className="mt-3 leading-7 text-slate-600">{survey.descricao}</p>}<div className="mt-8"><SurveyFlow questionnaireId={survey.id} questions={questions as SurveyQuestion[]}/></div></div></main>}
