"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRole } from "@/lib/auth/guards";
import { INTEREST_CATEGORIES } from "@/lib/consumer/categories";
import { createClient } from "@/lib/supabase/server";

export type AdminSurveyState={error?:string;success?:string};
const questionTypes=["single_choice","multiple_choice","short_text","scale"];
function optional(value:FormDataEntryValue|null){const text=String(value??"").trim();return text||null}
function surveyValues(formData:FormData){const interest=optional(formData.get("target_interest"));return {titulo:String(formData.get("titulo")??"").trim(),descricao:optional(formData.get("descricao")),estimated_minutes:Number(formData.get("estimated_minutes")),target_city:optional(formData.get("target_city")),target_neighborhood:optional(formData.get("target_neighborhood")),target_interest:interest&&INTEREST_CATEGORIES.includes(interest as typeof INTEREST_CATEGORIES[number])?interest:null,ativo:formData.get("ativo")==="on"}}
function validateSurvey(values:ReturnType<typeof surveyValues>){if(values.titulo.length<3)return "Informe um título com pelo menos 3 caracteres.";if(!Number.isInteger(values.estimated_minutes)||values.estimated_minutes<1||values.estimated_minutes>15)return "A estimativa deve ficar entre 1 e 15 minutos."}

export async function createSurveyAction(_state:AdminSurveyState,formData:FormData):Promise<AdminSurveyState>{await requireRole("admin");const values=surveyValues(formData);const invalid=validateSurvey(values);if(invalid)return {error:invalid};const supabase=await createClient();const {data,error}=await supabase.from("questionnaires").insert(values).select("id").single();if(error||!data)return {error:"Não foi possível criar o questionário."};redirect(`/admin/questionarios/${data.id}/editar`)}
export async function updateSurveyAction(_state:AdminSurveyState,formData:FormData):Promise<AdminSurveyState>{await requireRole("admin");const id=String(formData.get("id")??"");const values=surveyValues(formData);const invalid=validateSurvey(values);if(invalid)return {error:invalid};const supabase=await createClient();const {data:current}=await supabase.from("questionnaires").select("ativo").eq("id",id).single();if(!current)return {error:"Questionário não encontrado."};const {ativo,...metadata}=values;const {error}=await supabase.from("questionnaires").update(metadata).eq("id",id);if(error)return {error:"Não foi possível atualizar o questionário."};if(current.ativo!==ativo){const {error:statusError}=await supabase.rpc("admin_set_questionnaire_status",{p_questionnaire_id:id,p_active:ativo});if(statusError)return {error:ativo?"Adicione pelo menos uma pergunta antes de ativar.":"Não foi possível alterar o status."}}revalidatePath("/admin/questionarios");return {success:"Questionário atualizado."}}

function questionValues(formData:FormData){const tipo=String(formData.get("tipo")??"");const raw=String(formData.get("opcoes")??"").trim();let opcoes:unknown=null;if(tipo==="single_choice"||tipo==="multiple_choice")opcoes=[...new Set(raw.split("\n").map(item=>item.trim()).filter(Boolean))];if(tipo==="scale"){const [min,max]=raw.split("-").map(Number);opcoes={min:Number.isInteger(min)?min:1,max:Number.isInteger(max)?max:5}}return {pergunta:String(formData.get("pergunta")??"").trim(),tipo,opcoes}}
function validateQuestion(values:ReturnType<typeof questionValues>){if(values.pergunta.length<3)return "Informe a pergunta.";if(!questionTypes.includes(values.tipo))return "Escolha um tipo válido.";if((values.tipo==="single_choice"||values.tipo==="multiple_choice")&&(!Array.isArray(values.opcoes)||values.opcoes.length<2))return "Informe ao menos duas opções, uma por linha.";if(values.tipo==="scale"){const scale=values.opcoes as {min:number;max:number};if(scale.min<0||scale.max>10||scale.min>=scale.max)return "Use uma escala válida, como 1-5."}}
export async function createQuestionAction(_state:AdminSurveyState,formData:FormData):Promise<AdminSurveyState>{await requireRole("admin");const questionnaireId=String(formData.get("questionnaire_id")??"");const values=questionValues(formData);const invalid=validateQuestion(values);if(invalid)return {error:invalid};const supabase=await createClient();const {data:last}=await supabase.from("questionnaire_questions").select("ordem").eq("questionnaire_id",questionnaireId).order("ordem",{ascending:false}).limit(1).maybeSingle();const {error}=await supabase.from("questionnaire_questions").insert({...values,questionnaire_id:questionnaireId,ordem:(last?.ordem??0)+1});if(error)return {error:"Não foi possível adicionar a pergunta."};revalidatePath(`/admin/questionarios/${questionnaireId}/editar`);return {success:"Pergunta adicionada."}}
export async function updateQuestionAction(_state:AdminSurveyState,formData:FormData):Promise<AdminSurveyState>{await requireRole("admin");const id=String(formData.get("id")??"");const questionnaireId=String(formData.get("questionnaire_id")??"");const values=questionValues(formData);const invalid=validateQuestion(values);if(invalid)return {error:invalid};const supabase=await createClient();const {error}=await supabase.from("questionnaire_questions").update(values).eq("id",id).eq("questionnaire_id",questionnaireId);if(error)return {error:"Não foi possível atualizar a pergunta."};revalidatePath(`/admin/questionarios/${questionnaireId}/editar`);return {success:"Pergunta atualizada."}}
export async function deleteQuestionAction(_state:AdminSurveyState,formData:FormData):Promise<AdminSurveyState>{await requireRole("admin");const id=String(formData.get("id")??"");const questionnaireId=String(formData.get("questionnaire_id")??"");const supabase=await createClient();const {error}=await supabase.from("questionnaire_questions").delete().eq("id",id).eq("questionnaire_id",questionnaireId);if(error)return {error:"Não foi possível remover a pergunta."};revalidatePath(`/admin/questionarios/${questionnaireId}/editar`);return {success:"Pergunta removida."}}
export async function moveQuestionAction(formData:FormData){await requireRole("admin");const id=String(formData.get("id")??"");const questionnaireId=String(formData.get("questionnaire_id")??"");const direction=Number(formData.get("direction"));const supabase=await createClient();await supabase.rpc("move_questionnaire_question",{p_question_id:id,p_direction:direction});revalidatePath(`/admin/questionarios/${questionnaireId}/editar`)}
